export const GET_INGREDIENTS_LIST = "GET_INGREDIENT_LIST";
export const GET_CONSTRUCTOR_LIST = "GET_CONSTRUCTOR_LIST";
export const DELETE_CONSTRUCTOR_ITEM = "GET_CONSTRUCTOR_LIST";
export const COUNTER_CONSTRUCTOR_ITEM = "COUNTER_CONSTRUCTOR_ITEM";
export const GET_INGREDIENT_INFO = "GET_INGREDIENT_INFO";
export const DELETE_INGREDIENT_INFO = "DELETE_INGREDIENT_INFO";
export const ADD_PRODUCT_CONSTRUCTOR = "ADD_PRODUCT_CONSTRUCTOR";
export const CHANGE_PRODUCT_CONSTRUCTOR = "CHANGE_PRODUCT_CONSTRUCTOR";
export const GET_TOTAL_PRICE = "GET_TOTAL_PRICE";


