export const GET_INGREDIENTS_LIST = "GET_INGREDIENT_LIST";
export const GET_CONSTRUCTOR_LIST = "GET_CONSTRUCTOR_LIST";
export const DELETE_CONSTRUCTOR_ITEM = "GET_CONSTRUCTOR_LIST";
export const COUNTER_CONSTRUCTOR_ITEM = "COUNTER_CONSTRUCTOR_ITEM";

export const GET_INGREDIENT_INFO = "GET_INGREDIENT_INFO";
export const DELETE_INGREDIENT_INFO = "DELETE_INGREDIENT_INFO";
export const GET_ORDER_INFO = "GET_ORDER_INFO";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const ADD_PRODUCT_CONSTRUCTOR = "ADD_PRODUCT_CONSTRUCTOR";
export const CHANGE_PRODUCT_CONSTRUCTOR = "CHANGE_PRODUCT_CONSTRUCTOR";

export const GET_TOTAL_PRICE = "GET_TOTAL_PRICE";

export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_TOKEN = "AUTH_TOKEN";

export const GET_USER_INFO = "GET_USER_INFO";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";

export const IS_AUTH = 'IS_AUTH'
export const RESET_PASSWORD = 'RESET_PASSWORD'

